version: '3'
services: 
  mongo:
    image: mongo:3
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: teste
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
